openapi: '3.0.1'
info:
  title: 'Git push pull test'
  version: '1.0.0'
servers:
- url: 'https://dev-gm5er.wiremockapi.cloud'
paths:
  /things/{thingId}:
    get:
      operationId: 'getThingsByThingId'
      summary: 'Get things by thingId.'
      parameters:
      - in: 'path'
        name: 'thingId'
        schema:
          type: 'string'
        required: true
      responses:
        '200':
          description: 'Git push pull test stub 1'
          content:
            application/json:
              examples:
                Git push pull test stub 1:
                  value: |-
                    {
                      "stub" : 1
                    }
              schema:
                required:
                - stub
                type: object
                properties:
                  stub:
                    type: integer
                    format: int32
                    example: 1
                x-wiremock-hash: -879452980
    put:
      operationId: 'putThingsByThingId'
      summary: 'Put things by thingId.'
      parameters:
      - in: 'path'
        name: 'thingId'
        schema:
          type: 'string'
        required: true
      responses:
        '200':
          description: 'Git push pull test stub 2'
          content:
            application/json:
              examples:
                Git push pull test stub 2:
                  value: |-
                    {
                      "stub" : 2
                    }
              schema:
                required:
                - stub
                type: object
                properties:
                  stub:
                    type: integer
                    format: int32
                    example: 2
                x-wiremock-hash: -879452977
    delete:
      operationId: 'deleteThingsByThingId'
      summary: 'Delete things by thingId.'
      parameters:
      - in: 'path'
        name: 'thingId'
        schema:
          type: 'string'
        required: true
      responses:
        '200':
          description: 'Git push pull test stub 3'
          content:
            application/json:
              examples:
                Git push pull test stub 3:
                  value: |-
                    {
                      "stub" : 3
                    }
              schema:
                required:
                - stub
                type: object
                properties:
                  stub:
                    type: integer
                    format: int32
                    example: 3
                x-wiremock-hash: -879452974
